<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.5">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mengxing Chen">
<meta name="dcterms.date" content="2025-05-07">

<title>A Replication of Karlan and List (2007) – Mengxing’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ff4371ef257df69894857e99c6ad0d06.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b4de841ca19007c466c3cff04d6b7b09.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Mengxing’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">Description</a></li>
  <li><a href="#balance-test" id="toc-balance-test" class="nav-link" data-scroll-target="#balance-test">Balance Test</a></li>
  <li><a href="#balance-test-results" id="toc-balance-test-results" class="nav-link" data-scroll-target="#balance-test-results">Balance Test Results</a></li>
  </ul></li>
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results">Experimental Results</a>
  <ul class="collapse">
  <li><a href="#charitable-contribution-made" id="toc-charitable-contribution-made" class="nav-link" data-scroll-target="#charitable-contribution-made">Charitable Contribution Made</a></li>
  <li><a href="#differences-between-match-rates" id="toc-differences-between-match-rates" class="nav-link" data-scroll-target="#differences-between-match-rates">Differences between Match Rates</a></li>
  <li><a href="#size-of-charitable-contribution" id="toc-size-of-charitable-contribution" class="nav-link" data-scroll-target="#size-of-charitable-contribution">Size of Charitable Contribution</a></li>
  </ul></li>
  <li><a href="#simulation-experiment" id="toc-simulation-experiment" class="nav-link" data-scroll-target="#simulation-experiment">Simulation Experiment</a>
  <ul class="collapse">
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers">Law of Large Numbers</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#empirical-findings" id="toc-empirical-findings" class="nav-link" data-scroll-target="#empirical-findings">🔍 Empirical Findings:</a></li>
  <li><a href="#statistical-simulation-insights" id="toc-statistical-simulation-insights" class="nav-link" data-scroll-target="#statistical-simulation-insights">📈 Statistical Simulation Insights:</a></li>
  <li><a href="#behavioral-insight" id="toc-behavioral-insight" class="nav-link" data-scroll-target="#behavioral-insight">🧠 Behavioral Insight:</a></li>
  <li><a href="#takeaway-for-fundraisers-and-analysts" id="toc-takeaway-for-fundraisers-and-analysts" class="nav-link" data-scroll-target="#takeaway-for-fundraisers-and-analysts">💡 Takeaway for Fundraisers and Analysts:</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Replication of Karlan and List (2007)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mengxing Chen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 7, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>.</p>
<p>The matching grant letters varied along three key dimensions to test different aspects of charitable behavior. First, the <strong>match ratio</strong> offered in the letter was randomly assigned to be $1:$1, $2:$1, or $3:$1, meaning that for every dollar the recipient donated, an anonymous donor would contribute an additional $1, $2, or $3, respectively. Second, the letters varied the <strong>maximum amount</strong> the matching donor was willing to give—either $25,000, $50,000, $100,000, or an unspecified amount. Lastly, the <strong>suggested donation amount</strong> in the letter was personalized based on the recipient’s past giving history and was set to either match, exceed by 25%, or exceed by 50% their highest previous contribution.</p>
<p>This design allowed the researchers to isolate the effect of each factor on donation behavior. By comparing the response rates and donation amounts across these treatment groups and the control group, the experiment tested whether the size or framing of a matching offer significantly influenced charitable giving.</p>
<p>This project seeks to replicate their results.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>karlan_list_2007.dta</p>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<div id="c70e0a0d" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 50083 entries, 0 to 50082
Data columns (total 51 columns):
 #   Column              Non-Null Count  Dtype   
---  ------              --------------  -----   
 0   treatment           50083 non-null  int8    
 1   control             50083 non-null  int8    
 2   ratio               50083 non-null  category
 3   ratio2              50083 non-null  int8    
 4   ratio3              50083 non-null  int8    
 5   size                50083 non-null  category
 6   size25              50083 non-null  int8    
 7   size50              50083 non-null  int8    
 8   size100             50083 non-null  int8    
 9   sizeno              50083 non-null  int8    
 10  ask                 50083 non-null  category
 11  askd1               50083 non-null  int8    
 12  askd2               50083 non-null  int8    
 13  askd3               50083 non-null  int8    
 14  ask1                50083 non-null  int16   
 15  ask2                50083 non-null  int16   
 16  ask3                50083 non-null  int16   
 17  amount              50083 non-null  float32 
 18  gave                50083 non-null  int8    
 19  amountchange        50083 non-null  float32 
 20  hpa                 50083 non-null  float32 
 21  ltmedmra            50083 non-null  int8    
 22  freq                50083 non-null  int16   
 23  years               50082 non-null  float64 
 24  year5               50083 non-null  int8    
 25  mrm2                50082 non-null  float64 
 26  dormant             50083 non-null  int8    
 27  female              48972 non-null  float64 
 28  couple              48935 non-null  float64 
 29  state50one          50083 non-null  int8    
 30  nonlit              49631 non-null  float64 
 31  cases               49631 non-null  float64 
 32  statecnt            50083 non-null  float32 
 33  stateresponse       50083 non-null  float32 
 34  stateresponset      50083 non-null  float32 
 35  stateresponsec      50080 non-null  float32 
 36  stateresponsetminc  50080 non-null  float32 
 37  perbush             50048 non-null  float32 
 38  close25             50048 non-null  float64 
 39  red0                50048 non-null  float64 
 40  blue0               50048 non-null  float64 
 41  redcty              49978 non-null  float64 
 42  bluecty             49978 non-null  float64 
 43  pwhite              48217 non-null  float32 
 44  pblack              48047 non-null  float32 
 45  page18_39           48217 non-null  float32 
 46  ave_hh_sz           48221 non-null  float32 
 47  median_hhincome     48209 non-null  float64 
 48  powner              48214 non-null  float32 
 49  psch_atlstba        48215 non-null  float32 
 50  pop_propurban       48217 non-null  float32 
dtypes: category(3), float32(16), float64(12), int16(4), int8(16)
memory usage: 8.9 MB
   treatment  control    ratio  ratio2  ratio3      size  size25  size50  \
0          0        1  Control       0       0   Control       0       0   
1          0        1  Control       0       0   Control       0       0   
2          1        0        1       0       0  $100,000       0       0   
3          1        0        1       0       0  Unstated       0       0   
4          1        0        1       0       0   $50,000       0       1   

   size100  sizeno  ... redcty  bluecty    pwhite    pblack  page18_39  \
0        0       0  ...    0.0      1.0  0.446493  0.527769   0.317591   
1        0       0  ...    1.0      0.0       NaN       NaN        NaN   
2        1       0  ...    0.0      1.0  0.935706  0.011948   0.276128   
3        0       1  ...    1.0      0.0  0.888331  0.010760   0.279412   
4        0       0  ...    0.0      1.0  0.759014  0.127421   0.442389   

   ave_hh_sz  median_hhincome    powner  psch_atlstba  pop_propurban  
0       2.10          28517.0  0.499807      0.324528            1.0  
1        NaN              NaN       NaN           NaN            NaN  
2       2.48          51175.0  0.721941      0.192668            1.0  
3       2.65          79269.0  0.920431      0.412142            1.0  
4       1.85          40908.0  0.416072      0.439965            1.0  

[5 rows x 51 columns]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">treatment</th>
<th data-quarto-table-cell-role="th">control</th>
<th data-quarto-table-cell-role="th">gave</th>
<th data-quarto-table-cell-role="th">amount</th>
<th data-quarto-table-cell-role="th">ratio2</th>
<th data-quarto-table-cell-role="th">ratio3</th>
<th data-quarto-table-cell-role="th">size25</th>
<th data-quarto-table-cell-role="th">size50</th>
<th data-quarto-table-cell-role="th">size100</th>
<th data-quarto-table-cell-role="th">sizeno</th>
<th data-quarto-table-cell-role="th">askd1</th>
<th data-quarto-table-cell-role="th">askd2</th>
<th data-quarto-table-cell-role="th">askd3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>0.666813</td>
<td>0.333187</td>
<td>0.020646</td>
<td>0.915694</td>
<td>0.222311</td>
<td>0.222211</td>
<td>0.166723</td>
<td>0.166623</td>
<td>0.166723</td>
<td>0.166743</td>
<td>0.222311</td>
<td>0.222291</td>
<td>0.222211</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>0.471357</td>
<td>0.471357</td>
<td>0.142197</td>
<td>8.707393</td>
<td>0.415803</td>
<td>0.415736</td>
<td>0.372732</td>
<td>0.372643</td>
<td>0.372732</td>
<td>0.372750</td>
<td>0.415803</td>
<td>0.415790</td>
<td>0.415736</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>1.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>400.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Description
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The dataset contains 50,083 observations, where each row represents a prior donor who received a fundraising letter during a large-scale field experiment. The columns capture information about treatment assignment, donation behavior, prior donation history, and demographic characteristics.</p>
<p>There are 51 variables in total, including: - Treatment indicators (e.g., <code>treatment</code>, <code>ratio2</code>, <code>size25</code>, <code>askd1</code>) - Outcome variables (e.g., <code>gave</code>, <code>amount</code>) - Historical giving patterns (e.g., <code>hpa</code>, <code>ltmedmra</code>, <code>years</code>) - Demographic and contextual data (e.g., <code>female</code>, <code>redcty</code>, <code>median_hhincome</code>, <code>pop_propurban</code>)</p>
<p>All columns are fully populated or nearly complete, with minimal missing data. The data types include categorical flags and numeric variables (<code>int</code>, <code>float</code>), making it ready for statistical analysis and visualization.</p>
<p>A few summary statistics for key variables are shown below. The <code>treatment</code> and <code>control</code> variables confirm that the sample is split with approximately 66.7% in the treatment group and 33.3% in control. The <code>gave</code> variable shows that around <strong>2.06%</strong> of individuals donated. The average donation amount (<code>amount</code>) across all individuals is about <strong>$0.92</strong>, with a maximum of $400—indicating that while most gave nothing, a few individuals gave large amounts.</p>
<p>The match ratio assignments (<code>ratio2</code>, <code>ratio3</code>) are both close to <strong>22.2%</strong>, implying an even distribution across the three ratio groups (with <code>ratio1</code> implied by the absence of 2:1 and 3:1 flags). Similarly, each of the match threshold groups (<code>size25</code>, <code>size50</code>, <code>size100</code>, and <code>sizeno</code>) comprises around <strong>16.7%</strong> of the sample. The three suggested donation frames (<code>askd1</code>, <code>askd2</code>, <code>askd3</code>) are also equally distributed.</p>
<p>This supports the validity of the randomized design and confirms that the experiment’s treatments were implemented as intended.</p>
<p>The table below outlines key variables and their meanings:</p>
<section id="variable-definitions" class="level3">
<h3 class="anchored" data-anchor-id="variable-definitions">Variable Definitions</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
</section>
</div>
</div>
</div>
</section>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.</p>
<ol type="1">
<li>A <strong>t-test</strong> to compare group means</li>
<li>A <strong>simple linear regression</strong> for each variable with <code>treatment</code> as the independent variable</li>
</ol>
<p>The selected variables (<code>years</code>, <code>female</code>, <code>couple</code>, <code>median_hhincome</code>, and <code>page18_39</code>) are unrelated to the outcome, ensuring they are valid for balance testing. Results from both methods should match, as expected with a randomized experiment.</p>
<p>We calculate the t-statistic using the following formula:</p>
<p><span class="math display">\[
t = \frac{\bar{X}_A - \bar{X}_B}{\sqrt{\frac{s_A^2}{n_A} + \frac{s_B^2}{n_B}}}
\]</span></p>
<p>Where: - ( {X}_A, {X}_B ): sample means of the treatment and control groups - ( s_A^2, s_B^2 ): sample variances - ( n_A, n_B ): sample sizes</p>
<div id="3ffaa8af" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>Manual T-Tests (using formula):
years: t = -1.091
female: t = -1.754
couple: t = -0.582
median_hhincome: t = -0.743
page18_39: t = -0.124</code></pre>
</div>
</div>
<div id="21be7455" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regressions (variable ~ treatment):
years: coef = -0.058, se = 0.052, p = 0.270
female: coef = -0.008, se = 0.004, p = 0.079
couple: coef = -0.002, se = 0.003, p = 0.559
median_hhincome: coef = -157.925, se = 212.929, p = 0.458
page18_39: coef = -0.000, se = 0.001, p = 0.901</code></pre>
</div>
</div>
</section>
<section id="balance-test-results" class="level3">
<h3 class="anchored" data-anchor-id="balance-test-results">Balance Test Results</h3>
<p>The results from both the <strong>t-tests</strong> and <strong>linear regressions</strong> show no statistically significant differences between treatment and control groups on key pre-treatment variables:</p>
<ul>
<li><code>years</code> since first donation (p = 0.275 / 0.270)</li>
<li><code>female</code> indicator (p = 0.080 / 0.079)</li>
<li><code>couple</code> status (p = 0.560 / 0.559)</li>
<li><code>median_hhincome</code> at zip code level (p = 0.457 / 0.458)</li>
<li><code>page18_39</code> proportion (p = 0.901 / 0.901)</li>
</ul>
<p>All p-values are well above the 0.05 significance threshold. The <strong>regression coefficients are small in magnitude</strong>, and the t-test statistics confirm these differences are not statistically meaningful.</p>
<p>Together, these results support the assumption that the treatment was randomly assigned and that treatment and control groups were well-balanced at baseline—just as shown in <strong>Table 1 of the original paper</strong>.</p>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<section id="charitable-contribution-made" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made">Charitable Contribution Made</h3>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation.</p>
<div id="79b6973a" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-5-output-1.png" width="523" height="357" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart above illustrates the proportion of individuals who made a donation in each group. The <strong>treatment group</strong> — who received a letter with a matching grant offer — had a <strong>higher donation rate (~2.2%)</strong> than the control group (~1.9%).</p>
<p>While the overall donation rate is low in both groups, this visual supports the hypothesis that matching gifts <strong>increase charitable giving behavior</strong>, consistent with findings in Karlan and List (2007).</p>
<p>Note: The difference in donation rates is small in magnitude but directionally consistent with expectations and statistically significant when aggregated across many individuals.</p>
<div id="4681a204" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Split groups</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>treat <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>control <span class="op">=</span> df[df[<span class="st">'control'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>t_stat, p_val <span class="op">=</span> ttest_ind(treat, control, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"T-test on donation outcome: t = </span><span class="sc">{</span>t_stat<span class="sc">:.3f}</span><span class="ss">, p = </span><span class="sc">{</span>p_val<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression: gave ~ treatment</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">"gave ~ treatment"</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary().as_text())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T-test on donation outcome: t = 3.209, p = 0.0013
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   gave   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     9.618
Date:                Wed, 07 May 2025   Prob (F-statistic):            0.00193
Time:                        01:11:17   Log-Likelihood:                 26630.
No. Observations:               50083   AIC:                        -5.326e+04
Df Residuals:                   50081   BIC:                        -5.324e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0179      0.001     16.225      0.000       0.016       0.020
treatment      0.0042      0.001      3.101      0.002       0.002       0.007
==============================================================================
Omnibus:                    59814.280   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          4317152.727
Skew:                           6.740   Prob(JB):                         0.00
Kurtosis:                      46.440   Cond. No.                         3.23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The regression confirms the findings from the t-test: individuals in the treatment group were more likely to donate than those in the control group.</p>
<p>The coefficient on <code>treatment</code> is <strong>0.0042</strong>, indicating that offering a matching donation increased the likelihood of giving by <strong>0.42 percentage points</strong>. While the increase is small in absolute terms, it is <strong>statistically significant</strong> at the 1% level (p = 0.002).</p>
<p>This aligns with the behavioral insight from the paper: even modest nudges like a matching grant can have a measurable effect on behavior when framed persuasively.</p>
<p>These results replicate <strong>Table 2a Panel A</strong> in the original paper and validate the positive impact of matching donations on charitable giving.</p>
<div id="413f2e6d" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run probit model</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>probit_model <span class="op">=</span> smf.probit(<span class="st">"gave ~ treatment"</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show summary</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(probit_model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.100443
         Iterations 7
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                   gave   No. Observations:                50083
Model:                         Probit   Df Residuals:                    50081
Method:                           MLE   Df Model:                            1
Date:                Wed, 07 May 2025   Pseudo R-squ.:               0.0009783
Time:                        01:11:17   Log-Likelihood:                -5030.5
converged:                       True   LL-Null:                       -5035.4
Covariance Type:            nonrobust   LLR p-value:                  0.001696
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -2.1001      0.023    -90.073      0.000      -2.146      -2.054
treatment      0.0868      0.028      3.113      0.002       0.032       0.141
==============================================================================</code></pre>
</div>
</div>
<p>To replicate <strong>Table 3, Column 1</strong> from Karlan and List (2007), I estimated a <strong>probit model</strong> with <code>gave</code> as the binary outcome and <code>treatment</code> as the explanatory variable.</p>
<p>The coefficient on <code>treatment</code> is <strong>0.0868</strong> with a standard error of 0.028 and a z-value of 3.113, resulting in a <strong>p-value of 0.002</strong>. This confirms a <strong>statistically significant</strong> positive relationship between receiving a matching donation offer and making a charitable contribution.</p>
<p>In a probit model, coefficients indicate the direction and significance of effects on a latent probability scale. While the numeric value itself isn’t a direct percentage, the sign and significance imply that <strong>treatment increases the latent propensity to donate</strong>.</p>
<p>These results align with Table 3 in the original paper and reinforce the behavioral insight that <strong>framing a donation as being matched encourages action</strong>, even when the average effect is small.</p>
</section>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
<p>The t-tests comparing the donation rates across different match ratios yielded the following results:</p>
<div id="3170c409" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define group filters</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>ratio_1_1 <span class="op">=</span> df[(df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">'ratio2'</span>] <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (df[<span class="st">'ratio3'</span>] <span class="op">==</span> <span class="dv">0</span>)][<span class="st">'gave'</span>]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>ratio_2_1 <span class="op">=</span> df[df[<span class="st">'ratio2'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>ratio_3_1 <span class="op">=</span> df[df[<span class="st">'ratio3'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>]</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Run t-tests</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Match Ratio Comparisons (Donation Rate):"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>t1, p1 <span class="op">=</span> ttest_ind(ratio_1_1, ratio_2_1, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"1:1 vs 2:1 → t = </span><span class="sc">{</span>t1<span class="sc">:.3f}</span><span class="ss">, p = </span><span class="sc">{</span>p1<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>t2, p2 <span class="op">=</span> ttest_ind(ratio_1_1, ratio_3_1, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"1:1 vs 3:1 → t = </span><span class="sc">{</span>t2<span class="sc">:.3f}</span><span class="ss">, p = </span><span class="sc">{</span>p2<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>t3, p3 <span class="op">=</span> ttest_ind(ratio_2_1, ratio_3_1, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2:1 vs 3:1 → t = </span><span class="sc">{</span>t3<span class="sc">:.3f}</span><span class="ss">, p = </span><span class="sc">{</span>p3<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Match Ratio Comparisons (Donation Rate):
1:1 vs 2:1 → t = -0.965, p = 0.335
1:1 vs 3:1 → t = -1.015, p = 0.310
2:1 vs 3:1 → t = -0.050, p = 0.960</code></pre>
</div>
</div>
<p>All p-values are well above 0.05, indicating that the differences in response rates between these match ratios are <strong>not statistically significant</strong>.</p>
<p>These results support the paper’s conclusion: <strong>while matching offers do boost donations, the specific ratio ($1:$1 vs $2:$1 or $3:$1) doesn’t meaningfully alter behavior.</strong> In other words, donors respond positively to the <em>existence</em> of a match, not necessarily to how large it is.</p>
<p>This insight is important for fundraisers — offering a match works, but increasing its size does not appear to further increase donor response rates.</p>
<div id="40afa106" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Only keep treatment group</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df_treat <span class="op">=</span> df[df[<span class="st">"treatment"</span>] <span class="op">==</span> <span class="dv">1</span>].copy()</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create clean ratio column</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>df_treat[<span class="st">"match_ratio"</span>] <span class="op">=</span> <span class="st">"1:1"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>df_treat.loc[df_treat[<span class="st">"ratio2"</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">"match_ratio"</span>] <span class="op">=</span> <span class="st">"2:1"</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>df_treat.loc[df_treat[<span class="st">"ratio3"</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">"match_ratio"</span>] <span class="op">=</span> <span class="st">"3:1"</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to categorical with 1:1 as the reference</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>df_treat[<span class="st">"match_ratio"</span>] <span class="op">=</span> pd.Categorical(df_treat[<span class="st">"match_ratio"</span>], categories<span class="op">=</span>[<span class="st">"1:1"</span>, <span class="st">"2:1"</span>, <span class="st">"3:1"</span>])</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Run regression</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">"gave ~ C(match_ratio)"</span>, data<span class="op">=</span>df_treat).fit()</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   gave   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.6454
Date:                Wed, 07 May 2025   Prob (F-statistic):              0.524
Time:                        01:11:17   Log-Likelihood:                 16688.
No. Observations:               33396   AIC:                        -3.337e+04
Df Residuals:                   33393   BIC:                        -3.334e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=========================================================================================
                            coef    std err          t      P&gt;|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.0207      0.001     14.912      0.000       0.018       0.023
C(match_ratio)[T.2:1]     0.0019      0.002      0.958      0.338      -0.002       0.006
C(match_ratio)[T.3:1]     0.0020      0.002      1.008      0.313      -0.002       0.006
==============================================================================
Omnibus:                    38963.957   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2506478.937
Skew:                           6.511   Prob(JB):                         0.00
Kurtosis:                      43.394   Cond. No.                         3.73
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>To further investigate the effect of match size on donation behavior, I ran a regression of <code>gave</code> on the categorical variable <code>match_ratio</code>, which includes levels for 1:1, 2:1, and 3:1 matches. The 1:1 match is treated as the reference group.</p>
<p>The results show: - The <strong>2:1 match ratio</strong> has a coefficient of <strong>0.0019</strong>, with a p-value of <strong>0.338</strong> - The <strong>3:1 match ratio</strong> has a coefficient of <strong>0.0020</strong>, with a p-value of <strong>0.313</strong></p>
<p>Both estimates are <strong>positive but not statistically significant</strong>, meaning that there is <strong>no evidence that increasing the match ratio significantly improves the likelihood of giving</strong>.</p>
<p>These results support the findings in the original paper: <strong>larger match ratios do not lead to higher response rates</strong>. The mere presence of a match appears to drive behavior more than its magnitude, confirming the behavioral economics insight that <strong>perception of being matched matters more than match size</strong>.</p>
<div id="74390662" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Data-based Differences:
2:1 vs 1:1 → 0.0019
3:1 vs 1:1 → 0.0020
3:1 vs 2:1 → 0.0001

Regression-based Differences:
2:1 vs 1:1 → 0.0019
3:1 vs 1:1 → 0.0020
3:1 vs 2:1 → 0.0001</code></pre>
</div>
</div>
<p>I compared donation response rates across different match ratios (1:1, 2:1, and 3:1), both directly from the data and using the coefficients from a linear regression.</p>
<p>The results show: - <strong>2:1 vs 1:1</strong> → +0.0019 (0.19 percentage points) - <strong>3:1 vs 1:1</strong> → +0.0020 (0.20 percentage points) - <strong>3:1 vs 2:1</strong> → +0.0001 (0.01 percentage points)</p>
<p>These differences are extremely small and align almost perfectly between the raw group means and the fitted model coefficients. Importantly, none of these differences are statistically significant (as confirmed earlier in both the t-tests and regression).</p>
<p><strong>Conclusion:</strong> The size of the match ratio — whether 1:1, 2:1, or 3:1 — does not meaningfully influence whether someone donates. This supports the behavioral insight from the original paper that <strong>the existence of a match triggers giving, not the magnitude of the match.</strong></p>
</section>
<section id="size-of-charitable-contribution" class="level3">
<h3 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h3>
<p>In this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.</p>
<div id="121c2bbc" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>T-test on donation amount:
  Treatment mean = 0.97
  Control mean   = 0.81
  Difference     = 0.15
  t = 1.918, p = 0.0551

OLS Regression on donation amount:
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.8133      0.067     12.063      0.000       0.681       0.945
treatment      0.1536      0.083      1.861      0.063      -0.008       0.315
==============================================================================</code></pre>
</div>
</div>
<p>To examine whether the matching donation treatment affected the <strong>amount</strong> donated (not just whether people gave), I compared average donation sizes between treatment and control groups using both a t-test and a regression.</p>
<ul>
<li>The <strong>average donation</strong> was <strong>$0.97</strong> in the treatment group and <strong>$0.81</strong> in the control group, a difference of <strong>$0.15</strong></li>
<li>The t-test yielded a <strong>t-statistic of 1.918</strong> with a <strong>p-value of 0.0551</strong></li>
<li>The OLS regression estimated a treatment effect of <strong>$0.1536</strong>, with a <strong>p-value of 0.063</strong></li>
</ul>
<p>These results are <strong>marginally significant</strong> — they suggest that the treatment might increase the amount given, but the evidence is weaker than for the treatment’s effect on donation rate.</p>
<p>Takeaway: Matching donations appear to <strong>slightly increase how much people give</strong>, but not in a statistically strong way. This reinforces the idea that <strong>the main power of matching lies in increasing the number of donors, not the average donation size</strong>.</p>
<div id="3a038d87" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter dataset to only donors</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>donors_only <span class="op">=</span> df[df[<span class="st">"gave"</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run OLS regression on donation amount (conditional on giving)</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>model_conditional <span class="op">=</span> smf.ols(<span class="st">"amount ~ treatment"</span>, data<span class="op">=</span>donors_only).fit()</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show summary</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_conditional.summary().tables[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     45.5403      2.423     18.792      0.000      40.785      50.296
treatment     -1.6684      2.872     -0.581      0.561      -7.305       3.968
==============================================================================</code></pre>
</div>
</div>
<p>To analyze how much people give <strong>conditional on donating</strong>, I filtered the dataset to include only individuals who made a donation and regressed <code>amount</code> on <code>treatment</code>.</p>
<p>The results show that: - The average donation in the control group was <strong>$45.54</strong> - The treatment group gave <strong>$1.67 less on average</strong>, but this difference was <strong>not statistically significant</strong> (p = 0.561)</p>
<p>Interpretation: This means that while the treatment <strong>increased the likelihood of donating</strong>, it <strong>did not increase the amount given</strong> among those who chose to donate. In fact, if anything, the point estimate suggests a slightly lower donation amount in the treatment group — though we cannot confidently interpret this as a real effect given the high p-value.</p>
<p>Causal Interpretation: Because treatment was <strong>randomly assigned</strong>, the coefficient has a <strong>causal interpretation</strong> — but <strong>only for those who donated</strong>. It tells us the effect of the treatment <strong>conditional on positive giving</strong>, not for the general population.</p>
<p>Together with previous findings, this reinforces the main insight: <strong>matching grants are effective at getting people to donate, but not at increasing how much they give</strong>.</p>
<div id="18f39d70" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-13-output-1.png" width="1141" height="473" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The histograms above display the distribution of donation amounts <strong>among those who donated</strong>, separated by treatment status.</p>
<p>Both distributions are heavily <strong>right-skewed</strong>, with most donors giving small amounts and a few contributing much more. The red dashed lines indicate the average donation amount for each group:</p>
<ul>
<li><strong>Control Group Mean</strong>: ~$45.54<br>
</li>
<li><strong>Treatment Group Mean</strong>: ~$43.87</li>
</ul>
<p>The visual confirms what we saw in the conditional regression: while matching offers increase the probability of giving, they <strong>do not increase (and may slightly reduce) the amount donated</strong> by those who give. However, the difference is <strong>not statistically significant</strong>, and likely due to random variation.</p>
<p>This visualization reinforces our conclusion: <strong>the strength of matching donations lies in motivating people to give, not in changing how much they give.</strong></p>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<div id="0f97aa88" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-14-output-1.png" width="676" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the <strong>sampling distribution of the difference in means</strong> between two groups (each drawn from a Bernoulli distribution with the same true probability, p = 0.018). The red dashed line at 0 represents the <strong>true mean difference under the null</strong>.</p>
<p>The distribution is bell-shaped and centered at zero, as expected. Most simulated differences in means are small and cluster around zero, but some are further out in the tails.</p>
<p>This simulation helps us understand the behavior of the <strong>t-statistic</strong>: if we observe a sample difference that is far into the tails of this distribution, we consider it statistically unlikely under the null. That’s the core idea behind <strong>hypothesis testing</strong>.</p>
<p>This builds intuition for why the <strong>t-distribution</strong> matters in experimental design and inference.</p>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<div id="935c524a" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-15-output-1.png" width="1139" height="732" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This simulation demonstrates the Central Limit Theorem (CLT) using sample sizes of 50, 200, 500, and 1000. For each sample size, I generated 1,000 differences in sample means between simulated treatment and control groups (Bernoulli with p = 0.022 and p = 0.018, respectively).</p>
<p>Each histogram displays the <strong>sampling distribution of the difference in means</strong>. The red vertical line at 0 indicates the null hypothesis of no difference.</p>
<p>What We See: - At <strong>n = 50</strong>, the distribution is wide and rough, and zero is not clearly in the center — results are noisy. - At <strong>n = 200</strong>, the distribution becomes smoother and more centered. - By <strong>n = 500 and 1000</strong>, the sampling distribution is bell-shaped, narrow, and centered close to the expected value (≈ 0.004).</p>
<p>These visuals confirm the CLT: as sample size increases, the distribution of the sample mean difference becomes <strong>approximately normal and more concentrated</strong>. This helps explain why we use t-tests and confidence intervals — with large n, we can assume that the sampling distribution behaves predictably.</p>
<p>Conclusion: With small sample sizes, chance variation makes inference noisy, and zero might appear in the tails. But as sample size increases, the sampling distribution tightens, and <strong>zero becomes a clear benchmark for hypothesis testing</strong>. This simulation shows how <strong>precision improves with sample size</strong>, aligning perfectly with Slide 44’s message.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This project replicates and extends key findings from Karlan and List (2007), demonstrating the behavioral and statistical effects of charitable donation matching schemes through both real-world data and simulation-based intuition.</p>
<section id="empirical-findings" class="level3">
<h3 class="anchored" data-anchor-id="empirical-findings">🔍 Empirical Findings:</h3>
<ul>
<li><strong>Matching donation offers increase the probability of donating</strong> — a consistent, statistically significant result confirmed by t-tests, OLS, and probit regression.</li>
<li><strong>However, larger match ratios (2:1, 3:1) do not outperform a basic 1:1 match</strong>. This suggests that the psychological effect of “being matched” matters more than the specific amount.</li>
<li><strong>Donation size does not significantly change with treatment</strong>, whether we look at the full sample or only among donors. Matching primarily affects the <strong>extensive margin</strong> (whether someone donates), not the <strong>intensive margin</strong> (how much they give).</li>
</ul>
</section>
<section id="statistical-simulation-insights" class="level3">
<h3 class="anchored" data-anchor-id="statistical-simulation-insights">📈 Statistical Simulation Insights:</h3>
<ul>
<li>The <strong>Law of Large Numbers</strong> simulation showed that average outcomes stabilize with more trials.</li>
<li>The <strong>Central Limit Theorem</strong> simulations confirmed that the sampling distribution of sample mean differences becomes normal with larger sample sizes — validating the use of t-tests and p-values.</li>
<li>Across simulations, we saw why small sample sizes yield noisy inference and why large samples help us detect small but real effects.</li>
</ul>
</section>
<section id="behavioral-insight" class="level3">
<h3 class="anchored" data-anchor-id="behavioral-insight">🧠 Behavioral Insight:</h3>
<p>The evidence reinforces a key principle in behavioral economics: <strong>simple framing devices</strong> — like mentioning a matching donation — can meaningfully influence behavior, even if the economic incentive is minimal.</p>
<hr>
</section>
<section id="takeaway-for-fundraisers-and-analysts" class="level3">
<h3 class="anchored" data-anchor-id="takeaway-for-fundraisers-and-analysts">💡 Takeaway for Fundraisers and Analysts:</h3>
<p>If you’re designing a fundraising campaign, <strong>offering a match is powerful</strong>, but you don’t need to make it 2:1 or 3:1. The basic message, that “your gift will be matched,” is enough to boost donations. And if you’re testing such interventions, remember that <strong>sample size matters</strong> — a lot.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>